### ISSUE TITLE
Incorrect OAuth/Impersonation URL

### ISSUE THREAD

**Issue by cmainesGA** [docusign/sfdc-recipe-rest-create-envelope#1]
In step 2, the example URL for creating the impersonation authentication is: 
"https://accountd.docusign.com/oauth/..."
I believe it instead needs to be:
"https://account-d.docusign.com/oauth/..."

This matches the login URL for demo/sandbox accounts.

Additionally, when attempting to follow this instruction (adding the hyphen to the URL, and adding my integrator key for my demo account), I see a couple different error messages.

Upon first visiting the URL (already logged in) I see "DocuSign is temporarily unavailable. Please try again momentarily."
![image](https://user-images.githubusercontent.com/38292249/42390577-5a65a10a-811a-11e8-9d04-374f7890853c.png)

If I try to continue logging in, eventually I see "The redirect URI supplied in the request is not in the list of valid URIs configured with this client application."

![image](https://user-images.githubusercontent.com/38292249/42390626-89401fd2-811a-11e8-830d-b96bab147a61.png)

At this point, the url is "https://account-d.docusign.com/password?aspxerrorpath=%2Foauth%2Fauthresponse_type&scope=signature%20impersonation&client_id=REDACTED_API_ID&redirect_uri=https%3A%2Flocalhost.com#/password

While I have added the localhost domain as instructed, I wonder if the URL encoding is interfering with the matching.

![image](https://user-images.githubusercontent.com/38292249/42390721-db1ccf1c-811a-11e8-9678-270e7505d28f.png)

**Comment by vineetpuranik** [comment]
@cmainesGA 
Thanks for suggesting the URL correction. I have corrected it now.
For your concern with the redirect URI i can see that you have '#/password' at the end of the redirect URI and this is not matching with the URI specified in the integrator key. 
Both the redirect URI's should match exactly.
You can refer to the section 'Individually requesting permission' present under step 1 by navigating to the following site
https://developers.docusign.com/esign-rest-api/guides/authentication/oauth2-jsonwebtoken

Let us know if you are still facing the issue.

**Comment by cmainesGA** [comment]
Thanks @vineetpuranik  - the "#/password" is appended by the login flow after putting in my username. Attempting to remove it refreshes the page and starts again asking me for username.

**Comment by vineetpuranik** [comment]
@cmainesGA 
Can you let know if you have already signed in to DocuSign before attempting this step ? If not can you sign in and then open the URI in a new tab and try

**Comment by cmainesGA** [comment]
Yes, I tired signing in before hand in a different tab, similar behavior. I also attempted to add a Redirect URI of "https://localhost.com#/password" to see if that would satisfy the conditions, but no luck.

**Comment by vineetpuranik** [comment]
@cmainesGA 
Can you try with the following URL:
https://account-d.docusign.com/oauth/auth?
response_type=code&scope=signature%20impersonation&client_id=YOUR_KEY&redirect_uri=https://localhost.com

There was a '?' missing in the original URL. I have corrected the same

**Comment by vineetpuranik** [comment]
@cmainesGA 
Did you have a chance to look at my last comment and use the updated URL for impersonation

**Comment by vineetpuranik** [comment]
@nflearga 
Yes, this means that it has successfully granted the consent and then redirected you back to localhosturl.
We have added the localhost url just for demo. You could have added any redirect url as per your choice and then the redirection would have happened to that url

**Comment by nflearga** [comment]
Good to know. It will be helpful to adjust the readme in this recipe so that a "site can't be reached" message indicates success at the end of step 2. Currently the instructions indicate that a consent screen will be displayed.

**Comment by vineetpuranik** [comment]
@nflearga 
Yes, I just updated the readme file. Thanks for your inputs . Cheers :)

**Comment by vineetpuranik** [comment]
Thanks @nflearga  and @cmainesGA  for all your inputs. Closing this issue now
