### ISSUE TITLE
getAccessToken() returns error status code 400 instead of 200

### ISSUE THREAD

**Issue by nflearga** [docusign/sfdc-recipe-rest-create-envelope#2]
Following the readme to step 8 (Access Token Demo), the debug indicates an error. Do you have any guidance in debugging this? Thanks!

![dev console - status code 400](https://user-images.githubusercontent.com/39566678/42590537-175e09b4-8512-11e8-8304-062c6e3cfa0e.png)

**Comment by nflearga** [comment]
I repeated the instructions and had better luck the second time.

**Comment by vineetpuranik** [comment]
@nflearga sounds good :)
