### ISSUE TITLE
Example does not replicate "Send with DocuSign" button

### ISSUE THREAD

**Issue by gwdp** [docusign/sfdc-recipe-rest-create-envelope#6]
Hi There,

Checking the code because a client want to replicate the "Send with DocuSign" button action programmatically through apex triggers, but found that the code doesn't really replicate the button behaviour. 

I say that because "Send with DocuSign" sends the envelope and links the related object with the envelope, but I don't see being done on the code. Not relation with the related object is created and also I can't see DocuSign connect doing that because we don't specify any object ID on the requests.

My question would be, it's safe to manually grab the envelope ID, creating a DocuSign_Envelope Object on SF and linking to the related object? Any other suggestions for this?

**Comment by LarryKlugerDS** [comment]
I suggest checking out the DocuSign Apex toolkit for your project. 
See https://developers.docusign.com/salesforce

Unfortunately I don't know the answer to your other questions.

**Comment by gwdp** [comment]
Thanks @LarryKlugerDS this helps a lot! Does any apex classes documentation exists for the apex toolkit? Couldn't find it.

I believe you can close this issue for now.

**Comment by LarryKlugerDS** [comment]
Hi @gwdp , Here are the current docs: https://developers.docusign.com/salesforce/apex-toolkit-reference/index.html 
Also, check out https://www.youtube.com/watch?v=ZpHwlrRUMU4 and https://www.youtube.com/watch?v=0vpml8OJg6w

If you notice any shortcomings in the docs or the toolkit itself, please let us know via apihelp  at sign docusign.com
